import BreakingNews from "@/components/frontend/home/BreakingNews/BreakingNews";
import PopUpAd from "@/components/frontend/home/PopUpAd/PopUpAd";
import Footer from "@/components/frontend/Shared/footer/Footer";

import Navbar from "@/components/frontend/Shared/navbar/Navbar";
import TopAd from "@/components/frontend/TopAd/TopAd";

export const metadata = {
  title: "Daily Our Bangladesh",
  description: "Generated by Daily Our Bangladesh",
};
const MainLayout = ({ children }) => {
  return (
    <div>
      <TopAd />
      <PopUpAd />
      <Navbar />

      <BreakingNews />
      <div className="min-h-screen">{children}</div>
      <Footer />
    </div>
  );
};

export default MainLayout;
